/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 创建侧边栏使您能够：

 -创建一组有序的文档

 -为该组的每个文档呈现一个侧边栏

 -提供下一个/上一个导航


 边栏可以从文件系统生成，也可以在这里明确定义。


 创建任意数量的边栏。
 */


// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // nodeSidebar: [{type: 'autogenerated', dirName: '.'}]
  // But you can create a sidebar manually
  tutorialSidebar: [
      'what-is-Utility/cryptoeconomics',
      'what-is-Utility/blockchain',
      'what-is-Utility/computing-power-type',
      'what-is-Utility/computing-power-market',
      'what-is-Utility/network',
  ],
  nodeSidebar: [
    'node/introduction',
    'node/install',
    'node/start-node'
  ],
  powerSidebar: [
    'computing-power-supplier/introduce',
  ],
  dappSidebar: [
    'dapp/start',
  ],

};

export default sidebars;
