/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 创建侧边栏使您能够：

 -创建一组有序的文档

 -为该组的每个文档呈现一个侧边栏

 -提供下一个/上一个导航


 边栏可以从文件系统生成，也可以在这里明确定义。


 创建任意数量的边栏。
 */


// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    // nodeSidebar: [{type: 'autogenerated', dirName: '.'}]
    // But you can create a sidebar manually

    // 二级
    // tutorialSidebar: [
    //     {
    //         type: 'category',
    //         label: '简介',
    //         items: [
    //             'what-is-Utility/brief',
    //             'what-is-Utility/economics',
    //             'what-is-Utility/working',
    //             'what-is-Utility/computing_types',
    //             'what-is-Utility/rent',
    //             'what-is-Utility/network',
    //         ],
    //     }
    // ],

    // 三级
    tutorialSidebar: [
        'what-is-Utility/brief',
        {
            type: 'category',
            label: '链的工作方式',
            items: [
                // {
                //     type: 'category',
                //     label: 'synopsis 002',
                //     items: [
                //         // 'what-is-Utility/brief',
                //
                //         'what-is-Utility/working',
                //     ]
                // },

                'what-is-Utility/working',
                'what-is-Utility/bdc',

            ],
        },
        'what-is-Utility/economics',
        'what-is-Utility/computing_types',
        'what-is-Utility/rent',
        'what-is-Utility/network',
    ],
    nodeSidebar: [
        'node/introduction',
        'node/block',
        'node/coffer-data',
        'node/transaction',
        'node/coffer-engine',
        'node/install',
        'node/start-node',
        'node/params',
        'node/network',
        'node/sync',
        'node/safety',
        'node/monitor',
        'node/upgrade',
        'node/question',
        'node/rpc',
        'node/community',
    ],
    powerSidebar: [
        'computing-power-supplier/introduce',
        'computing-power-supplier/quick',
        'computing-power-supplier/init',
        'computing-power-supplier/claim',
        'computing-power-supplier/rent',
        'computing-power-supplier/pay',
        'computing-power-supplier/api',
        'computing-power-supplier/question',
        'computing-power-supplier/dev',
        'computing-power-supplier/community',
        'computing-power-supplier/history',
        'computing-power-supplier/legal',
    ],
    dappSidebar: [
        'dapp/start',
        'dapp/functions',
        'dapp/learn',
        'dapp/env',
        'dapp/build',
        'dapp/test',
        'dapp/deploy',
        'dapp/ref',
        'dapp/resources',
    ],
};

export default sidebars;
